name: appointment_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.14.0
  table_calendar: ^3.2.0

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  firebase_core: ^3.4.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  provider: ^6.1.5+1
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu.ttf
        - asset: assets/fonts/UbuntuBold.ttf
          weight: 700



flutter_native_splash:
  color: "#347FB6"
  android: true
  ios: true
  web: false
  android_12:
    color: "#347FB6"